# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - releases/*
    - test
  batch: true

variables:
  GIT_PAT: $(gitPat)
  AZURE_PAT: $(azurePass)

name: 1.0.$(Rev:r)

jobs:
- job: IOS
  displayName: Build_IOS
  pool:
    name: MAC
  steps:
  - checkout: self

  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'Certificates.p12'
      certPwd: 'Anygonow'
      keychain: 'temp'

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: 'Handyman.mobileprovision'

  - task: FlutterInstall@0
    inputs:
      mode: 'auto'
      channel: 'stable'
      version: 'latest'

  - task: CmdLine@2
    inputs:
      script: 'printf "SERVER_URL=%s\nUPDATE_VERSION_URL=%s\nUPDATE_VERSION_API=%s\n" "$SERVER_URL" "$UPDATE_VERSION_URL"  "$UPDATE_VERSION_API" > .env'

  - task: FlutterBuild@0
    inputs:
      target: 'ipa'
      projectDirectory: '.'
      extraArgs: '--release'
      buildName: "$(Build.BuildNumber)"
      exportOptionsPlist: 'ExportOptions.plist'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: IOS'
    inputs:
      PathtoPublish: 'build/ios/ipa'
      ArtifactName: mac

